apiVersion: v1
kind: Service
metadata:
  name: httpd-service-nautilus
spec:
  selector:
    app: httpd_app_nautilus
  ports:
    - port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment-nautilus
  labels:
    app: httpd_app_nautilus
spec:
  replicas: 4
  selector:
    matchLabels:
      app: httpd_app_nautilus
  template:
    metadata:
      labels:
        app: httpd_app_nautilus
    spec:
      containers:
        - name: httpd-container-nautilus
          image: httpd:latest
          ports:
            - containerPort: 80
---
kind: Ingress
metadata:
  name: minimal-ingress
  annotations:
    konghq.com/strip-path: 'true'    
spec:
  ingressClassName: kong 
  rules:
  - http:
      paths:
      - path: /testpath
        pathType: ImplementationSpecific
        backend:
          service:
            name: httpd-service-nautilus 
            port:
              number: 80
